type: google.api.Service
config_version: 3

name: hello.endpoints.agent-kit.cloud.goog

title: Hello API
apis:
- name: helloworld.Greeter

endpoints:
- name: hello.endpoints.agent-kit.cloud.goog
  target: "172.125.77.209"
