type: google.api.Service
config_version: 3
name: hello.endpoints.agentio.cloud.goog
title: Hello Endpoints Example API
apis:
- name: helloworld.Greeter
endpoints:
- name: hello.endpoints.agentio.cloud.goog
  target: "172.125.77.209"
backend:
  rules:
    - selector: "*"
      address: grpc://127.0.0.1:8080
      allow_unregistered_calls: true

